import { Shield, MessageSquareQuote, ArrowRight, Zap } from "lucide-react";

const objections = [
  {
    they: "How is this different from Heap?",
    you: [
      "Flat $200/mo vs Heap's $0–$3K/mo MTU-based pricing",
      "Snowflake/BigQuery sync native (Heap: paid add-on)",
      "30-min onboarding vs Heap's 3-week industry avg",
    ],
    proof: "Acme Health migrated from Heap in 4 days · saved $34K/yr",
  },
  {
    they: "Mixpanel is the standard - why switch?",
    you: [
      "Mixpanel pricing breaks at scale (per-MTU exponential growth)",
      "Self-serve PLG companies hit Mixpanel's 'enterprise wall' at ~$2K/mo",
      "Acme keeps flat pricing through 10M events/mo",
    ],
    proof: "Northwind cut analytics spend 73% post-switch",
  },
  {
    they: "We're already invested in Amplitude.",
    you: [
      "Acme's import tool ingests Amplitude event taxonomies in <30 min",
      "No re-instrumentation required (SDK compat layer ships v0.4)",
      "Run side-by-side for 30 days to validate data parity",
    ],
    proof: "Vertex AI migrated 18 months of historical data in one weekend",
  },
];

export function BattlecardWidget() {
  return (
    <div className="space-y-6">
      <div>
        <div className="text-[10px] font-mono uppercase tracking-widest text-pink">
          Battlecard v2 · Revenue Intelligence
        </div>
        <h3 className="mt-1 text-2xl font-semibold text-foreground">
          Competitive talk tracks
        </h3>
        <p className="mt-1.5 text-sm text-muted">
          Updated from 23 competitor losses (Q4 analysis). For every
          objection, the counter-positioning narrative plus the proof point a
          rep should drop in.
        </p>
      </div>

      <div className="space-y-4">
        {objections.map((o, i) => (
          <div
            key={i}
            className="overflow-hidden rounded-xl border border-border-accent bg-surface"
          >
            {/* They say */}
            <div className="flex items-start gap-3 border-b border-border bg-danger/5 p-4">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-danger/15 text-danger ring-1 ring-danger/30">
                <MessageSquareQuote className="h-4 w-4" />
              </div>
              <div className="flex-1">
                <div className="text-[10px] font-mono uppercase tracking-wider text-danger">
                  When they say
                </div>
                <div className="mt-1 text-sm font-medium italic text-foreground">
                  &ldquo;{o.they}&rdquo;
                </div>
              </div>
            </div>

            {/* You say */}
            <div className="p-4">
              <div className="flex items-start gap-3">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-success/15 text-success ring-1 ring-success/30">
                  <Shield className="h-4 w-4" />
                </div>
                <div className="flex-1">
                  <div className="text-[10px] font-mono uppercase tracking-wider text-success">
                    You say
                  </div>
                  <ul className="mt-2 space-y-1.5">
                    {o.you.map((point, j) => (
                      <li key={j} className="flex items-start gap-2 text-sm text-foreground">
                        <ArrowRight className="mt-1 h-3 w-3 shrink-0 text-success" />
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Proof point */}
              <div className="mt-4 ml-11 flex items-start gap-2 rounded-md border border-violet/30 bg-violet/10 p-3">
                <Zap className="mt-0.5 h-3.5 w-3.5 shrink-0 text-violet" />
                <div className="text-xs text-foreground">
                  <span className="text-violet font-mono uppercase tracking-wider text-[10px] mr-2">
                    Proof
                  </span>
                  {o.proof}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-border bg-background p-3 text-center font-mono text-[11px] text-muted">
        Generated by <span className="text-foreground">Oracle</span> from
        chi-square pattern analysis on 23 Q4 competitive losses.
      </div>
    </div>
  );
}
